### ISSUE TITLE
Baseline  is not well configured for moose image

### ISSUE THREAD

**Issue by mahugnon** [PolyMathOrg/DataFrame#101]
An error occurs well loading the project in a new moose Image

**Comment by SergeStinckwich** [comment]
Normally, the baseline is done to be loaded in a basic Pharo 7.0 image. Do you need to load it in a Moose image ?

**Comment by mahugnon** [comment]
Mais si je suis  déjà  dans une  image  moose7.  Il me cherche  encore
moose7.

Le jeu. 20 juin 2019 à 17:43, Serge Stinckwich <notifications@github.com> a
écrit :

**Comment by SergeStinckwich** [comment]
Can you speak in English, this is better for communication here.

**Comment by mahugnon** [comment]
Sorry, Yes. I understand. I fixed it in my image but. I wanted to notify.
Ok then

Le ven. 21 juin 2019 à 10:47, Serge Stinckwich <notifications@github.com> a
écrit :

**Comment by olekscode** [comment]
Baseline supports Pharo 6, 7, 8
I think, it is important that we also support Moose
Because _"Moose is a platform for software and data analysis"_ and _"DataFrame is a tabular data structure for data analysis"_ :)

**Comment by olekscode** [comment]
@mahugnon How did you fix it in your image?

**Comment by mahugnon** [comment]
If manually: You forget the repo Moose on Iceberg.
Programmatically :
You define this:
Baseline >> customProjectAttributes [ self class environment at:
#MooseEntity ifAbsent: [ ^ #(#WithoutMoose) ]. ^ #()].
Now you define two spec
spec for: #common and  spec for: #WithoutMoose
