### ISSUE TITLE
Tests failing on Pharo 8.0

### ISSUE THREAD

**Issue by AtharvaKhare** [PolyMathOrg/DataFrame#108]
18 tests are failing on Pharo 8.0.

This is due to https://github.com/pharo-project/pharo/pull/3537.

Solution: Replace `NotFoundError` with `LibrarySymbolNotFoundError`

**Comment by olekscode** [comment]
Yes, I am fixing it

**Comment by olekscode** [comment]
Done, all tests are green on all images.
