### ISSUE TITLE
How to deal with missing data for inducing types ?

### ISSUE THREAD

**Issue by SergeStinckwich** [PolyMathOrg/DataFrame#14]
If you have a column with missing data (with nil values) and this is often the case, the ```DataTypeInductor``` is not able to deduce the type of the column. How do we deal with that ?

**Comment by philippeback** [comment]
In R there is the NA thing and the is.na test.

https://stat.ethz.ch/R-manual/R-devel/library/base/html/NA.html

http://www.statmethods.net/input/missingdata.html

Also see: mean(x, na.rm=TRUE)

We should have that in DataSeries for aggregates.

**Comment by AtharvaKhare** [comment]
Fixed with https://github.com/PolyMathOrg/DataFrame/pull/107
