### ISSUE TITLE
Implement a Spec UI that would display DataFrame as a table

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#147]
- Columns should be sortable
- Columns should be resizable
- It would be nice (if possible) to hide/show columns
- It should not crash on large data frames (lazy loading)

**Comment by hernanmd** [comment]
Something like this https://github.com/pharo-ai/data-inspector ?

**Comment by SergeStinckwich** [comment]
Yes would be great for Pharo 9.

**Comment by jordanmontt** [comment]
@SergeStinckwich @hernanmd  @olekscode do you think that we should include data-inspector bu default in DataFrame?

- One option is to add a dependency to the baseline
- The other one is to copy the code to DataFrame and to delete the repo of pharo-ai

What do you think?

**Comment by hernanmd** [comment]
For me I vote to add the dependency to the Baseline, this way we don't overpopulate DataFrame and the UI tool is separated from DataFrame.

**Comment by jordanmontt** [comment]
I propose to close this since we alredy have:
- The DataFrame inspector tool that Martin did
- the data frame inspector in pharo-ai that containts statistics and also visualisations
