### ISSUE TITLE
Remove the methods that define a FastTable tab in GTInspector

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#148]
This tab does not work anymore in the recent versions of Pharo.
We should have a Spec view for DataFrame now (see issue #147).

Methods to be removed are in the `gt-inspector-extension` protocol:

- `DataFrame >> gtInspectorFastTableIn:`
- `DataFrame >> gtInspectorItemsIn:`
- `DataFrame >> showWithGlamourIn:`

**Comment by khinsen** [comment]
Isn't it a bit early for deleting support for Pharo 8? That's probably still what most people use.

**Comment by tinchodias** [comment]
Hi, I've done it. I'll let you for review in a moment,
