### ISSUE TITLE
Missing dependency for NeoCSV

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#19]
After DataFrame was loaded, NeoCSV has to be installed manually from Catalog Browser. This dependency must be added to the BaselineOfDataFrame.

It doesn't raise an error when DataFrame is loaded. But if you call `DataFrame >> fromCSV:`, you'll get an error saying that "on: was sent to nil"

**Comment by Ducasse** [comment]
Hi oleks
Think differently.
You have a package DataFrame
And then you have another package DataFrameXXX which depends on DataFrame and others 
Please do not like dataFrame to other packages dirrectly.

Stef
