### ISSUE TITLE
Feature Request: addRow:

### ISSUE THREAD

**Issue by GrahamMcLeod** [PolyMathOrg/DataFrame#2]
It would be great to have an addRow: 
capability which would simply append a new row to the dataFrame. 
I tried trivially adding one, but it seems the data structure is fixed size and one may have to copy 
the whole frame to achieve this, something one wants to avoid for performance reasons. 
Is there an easy way to add in the implementation?
Thanks
Graham

**Comment by olekscode** [comment]
Hello!
Thanks for your request.

I have implemented `addRow:named` and `addColumn:named:` messages for DataFrame and `add:atKey:` message for DataSeries. Alternatively, you can use `row:put:`, `column:put:`, and `atKey:put:` messages for adding new elements. You can read more about these messages in these sections of tutorial:
1. [Adding new elements to DataSeries](https://github.com/PolyMathOrg/DataFrame#adding-new-elements-to-dataseries)
2. [Adding new rows and columns to DataFrame](https://github.com/PolyMathOrg/DataFrame#adding-new-rows-and-columns-to-dataframe) 

The data structures still have fixed size, so every time you add new rows to DataFrame or new elements to DataSeries, the contents of the old collection is being copied to the new one. I do plan to change this when I will be working on performance issues. But this will be after ESUG.
