### ISSUE TITLE
DataSeries>>#uniqueValues should not sort 

### ISSUE THREAD

**Issue by jecisc** [PolyMathOrg/DataFrame#203]
Sorting is not something to do at this level. We lose perf and most of the time we don't care about the fact that this is sorted

**Comment by Joshua-Dias-Barreto** [comment]
@jecisc few existing methods need the unique values to be sorted such as `crossTabulateWith:` and other grouping methods. We can either make a new method `uniqueValuesUnsorted` and leave all other methods as they are or we can define a new method `uniqueValuesSorted` and change all other methods that need the unique values to be sorted.

**Comment by jecisc** [comment]
In general it is good if an algo do not **need** to be sorted, to not sort and let users needing sorting to sort themselves.

I think I would add a method #sortIfPossible to do the sort, and call `receiver uniqueValues sortIfPossible` where we need the sorting
