### ISSUE TITLE
DataFrame can not be initialized with missing values

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#21]
It would be useful to initialize a `DataFrame` with the following "incomplete" array and have it automatically insert `nil` or `Float nan` in place of the missing values. It should also be possible to handle these values later.

```Smalltalk
DataFrame fromRows: #(
    (1 2 3)
    (4 5)).
```

**Comment by SergeStinckwich** [comment]
A better support for missing values like the one you can find in R or Python is needed.
