### ISSUE TITLE
Handling missing data

### ISSUE THREAD

**Issue by Joshua-Dias-Barreto** [PolyMathOrg/DataFrame#221]
The only methods missing which would make handling missing data in Pharo DataFrames same as in pandas Dataframes are the **replaceNilsWithNextValue** and **replaceNilsWithNextRowValue** these methods will be equivalent to the [ffil()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ffill.html) method in pandas.

**Comment by olekscode** [comment]
Do we have a chapter on missing values in the booklet?
If not, you should write it :)

It would be a great exercise and missing values are an important topic that needs to be documented.

Talk about that with @jecisc 
Then, if he agrees, add this in your plan, and write a guide on missing values in plain Markdown

We will then integrate it into the booklet, which should be migrated to Microdown at some point
And we can also add it to [Pharo Wiki](https://github.com/pharo-open-documentation/pharo-wiki)
