### ISSUE TITLE
 Add toCategorical and toCategoricalNumberCategories: in the DataSeries class.

### ISSUE THREAD

**Issue by Joshua-Dias-Barreto** [PolyMathOrg/DataFrame#222]
**toCategorical:** would be beneficial for one - hot encoding data and categorization of data. If the number of categories is not specified, the number of categories would be the maximum value of the Data Series + 1. If the user wants a specified number of categories, **toCategoricalNumberCategories :** can be used. This would be similar to TensorFlow's [keras.utils.to_categorical()](https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical)

**Comment by olekscode** [comment]
Could you please provide an example of how this method would be used?
You can even write it directly as a test:
```st
testToCategorical
    | series expected |
    
    series := ... "(or data frame?)"
    
    expected := ...
    
    self assert: series toCategorical equals: expected.
```
And the same for `toCategoricalNumberCategories`

This would help us understand the usage scenario and the expected behaviour of the new methods that you propose

**Comment by Joshua-Dias-Barreto** [comment]
This is a test for `toCategorical`

	testToCategorical
        | series expected |
	series := DataSeries
		          withKeys: #( 'A' 'B' 'C' 'D' )
		          values: #( 0 1 2 3 )
		          name: series.
	expected := DataSeries
		            withKeys: #( 'A' 'B' 'C' 'D' )
		            values:
		            #( #( 1 0 0 0 ) #( 0 1 0 0 ) #( 0 0 1 0 ) #( 0 0 0 1 ) )
		            name: series.
	self assert: series toCategorical equals: expected
