### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#224]
I think we should make our README a bit more attractive

- Add a bit more text to the first paragraph. For now, there is only _"DataFrame is a tabular data structure for data analysis in Pharo"_. We should add 2-3 more sentences there (they can be taken from [What are data frames](https://github.com/PolyMathOrg/DataFrame#what-are-data-frames) section)
- Remove the first image. It is outdated, it still shows FastTable which was removed long time ago. We should either update it with a new screenshot, or show DataInspector, or a combination of some tables, charts, playgrounds, etc. ... in other words, it is the first thing people see and I think it should be more attractive
- The screenshots in the [Very Simple Example](https://github.com/PolyMathOrg/DataFrame#very-simple-example) section are low-quality. We should always have higher DPI when we put screenshots somewhere. Besides, I don't like the idea of using screenshots to demonstrate output. They are not editable and quickly get outdated. And they are not attractive at all because the current Spec table that we have in the inspector is not that aesthetic. So I would rather use the Markdown tables to demonstrate the output
- Instead of the [DataFrame booklet](https://github.com/PolyMathOrg/DataFrame#dataframe-booklet), I would write a "Documentation & Literature" section listing booklets, wikis, tutorials, blogs, and papers.

**Comment by Joshua-Dias-Barreto** [comment]
Fixed by PR #243.
