### ISSUE TITLE
Statistical methods in DataSeries should handle nils

### ISSUE THREAD

**Issue by Joshua-Dias-Barreto** [PolyMathOrg/DataFrame#227]
Currently, few statistical methods signal errors when nils are present in the dataseries such as `stdev` `median` `min` `max`

**Comment by Joshua-Dias-Barreto** [comment]
@jecisc should I add these methods to the DataSeries class so that they ignore nils, similar to what is done with the `average` method.

    ^ (self values reject: #isNil) average

**Comment by jecisc** [comment]
Yes, the nil checks should be done in the data series
