### ISSUE TITLE
Last column name not displayed in inspector

### ISSUE THREAD

**Issue by philippeback** [PolyMathOrg/DataFrame#4]
![image](https://user-images.githubusercontent.com/2128441/30525061-802c6406-9bff-11e7-90bd-5587bead87fb.png)

df columnNames: #(Numerator Denumerator Fraction AsFloat).

But the "AsFloat" entry is not showing.

**Comment by olekscode** [comment]
I think this is a problem with FastTable. When you open this table in a window, the last column name is visible, but when you resize the window - it disappears. I will ask people on Discord what can be the reason for that and try to fix it

**Comment by olekscode** [comment]
Fixed (sort of) by setting the width for each column
