### ISSUE TITLE
Provide sorting

### ISSUE THREAD

**Issue by khinsen** [PolyMathOrg/DataFrame#43]
A feature I missed during my first experiments with DataFrame is sorting. I'd expect the most general sorting operation to be `sort: aBlock`, like for `SequenceableCollection`, but the practically more frequent operation would be sorting by column.

**Comment by khinsen** [comment]
I just discovered by accident that sorting by column is already available, but it's called `orderBy:` rather than something starting with `sort`. I think it would preferable to stick to the naming conventions used by the standard Pharo collections.

**Comment by olekscode** [comment]
I was following the conventions of SQL
But now I fully agree with you
It should be sort

**Comment by olekscode** [comment]
New API for sorting:
```Smalltalk
series sort.
series sortDescending.
series sortUsing: aBlock.

dataFrame sortBy: columnName.
dataFrame sortDescendingBy: columnName.
dataFrame sortBy: columnName using: aBlock.
```

**Comment by khinsen** [comment]
Great, thanks!
