### ISSUE TITLE
Add JSON read/write support

### ISSUE THREAD

**Issue by AtharvaKhare** [PolyMathOrg/DataFrame#97]
`​DataFrameJsonReader` and `​DataFrameJsonWriter` need to be implemented, along with its tests, and examples. We can use `NeoJSON` library for this purpose. It will make using internet APIs as data-source easier.

Related issue: https://github.com/SquareBracketAssociates/Booklet-DataFrame/issues/1

**Comment by khinsen** [comment]
That's a very good idea. The JSON format should be compatible with the one used by R as much as possible. At least for numerical and string data, but ideally also for dates and some other common data types.
